export enum AppShellActions {
  WATCH_CONNECTION_STATE = 'WATCH_CONNECTION_STATE',
  UNWATCH_CONNECTION_STATE = 'WATCH_CONNECTION_STATE',
  UPDATE_CONNECTION_STATE = 'UPDATE_CONNECTION_STATE',
  UPDATE_CONNECTION_INFO = 'UPDATE_CONNECTION_INFO'
}


